Completed sql-select
John-Baik/rc1021-code-solutions pull request #95
Opened 2021-12-03 23:18 UTC by John-Baik

![image](https://user-images.githubusercontent.com/90541276/144684999-c4c6a5d9-ca81-4ccd-a201-9fd1f59abe2a.png)

2021-12-03 23:45 UTC, TimelikeClosure requested changes
@John-Baik Please include screenshots of the results generated by executing the queries.

2021-12-03 23:58 UTC, John-Baik commented
![image](https://user-images.githubusercontent.com/90541276/144686909-57d59b9a-e5c0-49a9-bd37-ceed2fbdd28d.png)
![image](https://user-images.githubusercontent.com/90541276/144686955-e41af7ec-502b-44f6-b237-0e44f48782b4.png)
![image](https://user-images.githubusercontent.com/90541276/144686995-293abeb9-b17e-4e01-8d64-d8b2474139b2.png)
![image](https://user-images.githubusercontent.com/90541276/144687034-cb8369e0-c32c-427d-829b-6431e16b1f0b.png)
![image](https://user-images.githubusercontent.com/90541276/144687067-4ed21549-e489-4adb-83d9-048aee903386.png)
![image](https://user-images.githubusercontent.com/90541276/144687087-5034f770-9f87-4c0d-9bac-ab36e7110c4e.png)
![image](https://user-images.githubusercontent.com/90541276/144687111-b0e7debd-6e0b-41af-930a-b2648b3eea3f.png)
![image](https://user-images.githubusercontent.com/90541276/144687196-efa77f35-4e2f-460b-9eb3-1d2ead5c54de.png)
![image](https://user-images.githubusercontent.com/90541276/144687212-175f32e4-ef8f-4d9b-ae74-6ff019b331ca.png)
![image](https://user-images.githubusercontent.com/90541276/144687238-a94659a0-fa45-4fd5-ba59-361b19f47035.png)
![image](https://user-images.githubusercontent.com/90541276/144687270-b838e414-1995-42cd-85a6-3a065873bf86.png)
![image](https://user-images.githubusercontent.com/90541276/144687302-ca6102b2-8eca-4c11-83b0-bb4f0347a0f4.png)
![image](https://user-images.githubusercontent.com/90541276/144687313-e89b30ee-58b4-46a9-a764-56012c3bd004.png)
![image](https://user-images.githubusercontent.com/90541276/144687343-dff338ce-7191-4079-a999-f428ced0cd6c.png)
![image](https://user-images.githubusercontent.com/90541276/144687424-a83f1130-f9dd-4953-bae3-071cc0a10c4b.png)
![image](https://user-images.githubusercontent.com/90541276/144687462-cd7ccaef-7dec-4e47-8004-2be38f6ac44b.png)
![image](https://user-images.githubusercontent.com/90541276/144687485-0321f92f-f3e0-45f4-9d4b-acd2e45520be.png)
![image](https://user-images.githubusercontent.com/90541276/144687510-964f300c-123e-4fb1-83a9-fbd5a1e24939.png)

2021-12-04 00:08 UTC, TimelikeClosure approved these changes

2021-12-04 00:08 UTC, TimelikeClosure commented on sql-select/list-of-databases.txt
> +
This was only necessary for the first two exercises

2021-12-04 00:08 UTC, merged